#!/bin/bash
#$ -N cpu_test 
# -pe mpi 4 
#$ -q nodes.q
#$ -j y
#$ -cwd 
#$ -l h="node02"

#directory of excutable
DIR=`pwd`
echo $DIR

source /etc/profile.d/modules.sh
source /home/zgao/.bashrc

mpirun -np 1 --rank-by core $DIR/mpi_hw.cx
