#!/bin/bash
#$ -N stream_test 
#$ -pe mpi 16
#$ -q all.q
#$ -j y
#$ -R y
#$ -cwd 

#directory of excutable
DIR=`pwd`
echo $DIR

source /etc/profile.d/modules.sh
source /home/zgao/.bashrc

echo "mpirun -np $1 $DIR/mpi_stream.cx"
mpirun -np $1 $DIR/mpi_stream.cx
