#!/bin/bash
#$ -N petsc_test 
#$ -pe mpi 64 
#$ -q nodes.q
#$ -j y
#$ -R y
#$ -cwd 
# -l h="node01|node02"

#directory of excutable
DIR=`pwd`

ulimit -s unlimited

source /etc/profile.d/modules.sh
source /home/zgao/.bashrc
#run options
mpirun -np ${NP} ${DIR}/mpi_petsc.cx -m 4000 -n 4000 -pc_type hypre -pc_hypre_type boomeramg -ksp_type gmres -ksp_monitor -log_summary
